### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by angelo-peronio** [JamesALeedham/Sphinx-Autosummary-Recursion#2]
Thank you for this very useful example!

Would you mind adding a [license](https://choosealicense.com/)? So I can know whether I am allowed to take from it.

**Comment by JamesALeedham** [comment]
Hey Angelo, glad it was useful and you are of course welcome to do anything you like with it.

I'm not an expert but the MIT license seems the most suitable/permissive..? I'll upload a copy tomorrow...

**Comment by JamesALeedham** [comment]
MIT license added.

**Comment by angelo-peronio** [comment]
Great! Thank you.
